# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: versioning-rollback/version_control.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'versioning-rollback/version_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)versioning-rollback/version_control.proto\"(\n\x0f\x46unctionRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\"#\n\x10RollbackResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"K\n\x0e\x43ompareRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x10\n\x08version1\x18\x02 \x01(\t\x12\x10\n\x08version2\x18\x03 \x01(\t\"0\n\x06\x43hange\x12\x0c\n\x04line\x18\x01 \x01(\x05\x12\x0b\n\x03old\x18\x02 \x01(\t\x12\x0b\n\x03new\x18\x03 \x01(\t\"+\n\x0f\x43ompareResponse\x12\x18\n\x07\x63hanges\x18\x01 \x03(\x0b\x32\x07.Change2\x97\x01\n\x15VersionControlService\x12@\n\x19RollbackToPreviousVersion\x12\x10.FunctionRequest\x1a\x11.RollbackResponse\x12<\n\x17\x43ompareFunctionVersions\x12\x0f.CompareRequest\x1a\x10.CompareResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'versioning_rollback.version_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FUNCTIONREQUEST']._serialized_start=45
  _globals['_FUNCTIONREQUEST']._serialized_end=85
  _globals['_ROLLBACKRESPONSE']._serialized_start=87
  _globals['_ROLLBACKRESPONSE']._serialized_end=122
  _globals['_COMPAREREQUEST']._serialized_start=124
  _globals['_COMPAREREQUEST']._serialized_end=199
  _globals['_CHANGE']._serialized_start=201
  _globals['_CHANGE']._serialized_end=249
  _globals['_COMPARERESPONSE']._serialized_start=251
  _globals['_COMPARERESPONSE']._serialized_end=294
  _globals['_VERSIONCONTROLSERVICE']._serialized_start=297
  _globals['_VERSIONCONTROLSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
