# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import list_delete_pb2 as list__delete__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in list_delete_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class listDeleteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listFunctionVersions = channel.unary_unary(
                '/listDelete/listFunctionVersions',
                request_serializer=list__delete__pb2.listFunctionRequest.SerializeToString,
                response_deserializer=list__delete__pb2.functionListVersionsResponse.FromString,
                _registered_method=True)
        self.deleteFunction = channel.unary_unary(
                '/listDelete/deleteFunction',
                request_serializer=list__delete__pb2.deleteFunctionRequest.SerializeToString,
                response_deserializer=list__delete__pb2.deleteFunctionResponse.FromString,
                _registered_method=True)


class listDeleteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listFunctionVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_listDeleteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listFunctionVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.listFunctionVersions,
                    request_deserializer=list__delete__pb2.listFunctionRequest.FromString,
                    response_serializer=list__delete__pb2.functionListVersionsResponse.SerializeToString,
            ),
            'deleteFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteFunction,
                    request_deserializer=list__delete__pb2.deleteFunctionRequest.FromString,
                    response_serializer=list__delete__pb2.deleteFunctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'listDelete', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('listDelete', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class listDelete(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listFunctionVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listDelete/listFunctionVersions',
            list__delete__pb2.listFunctionRequest.SerializeToString,
            list__delete__pb2.functionListVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listDelete/deleteFunction',
            list__delete__pb2.deleteFunctionRequest.SerializeToString,
            list__delete__pb2.deleteFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
