# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: function_version.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'function_version.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66unction_version.proto\x12\x0f\x66unctionservice\"%\n\x11GetVersionRequest\x12\x10\n\x08\x66unction\x18\x01 \x01(\t\"%\n\x12GetVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\"6\n\x11SetVersionRequest\x12\x10\n\x08\x66unction\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"%\n\x12SetVersionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe2\x01\n\x16\x46unctionVersionService\x12\x63\n\x18GetActiveFunctionVersion\x12\".functionservice.GetVersionRequest\x1a#.functionservice.GetVersionResponse\x12\x63\n\x18SetActiveFunctionVersion\x12\".functionservice.SetVersionRequest\x1a#.functionservice.SetVersionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'function_version_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETVERSIONREQUEST']._serialized_start=43
  _globals['_GETVERSIONREQUEST']._serialized_end=80
  _globals['_GETVERSIONRESPONSE']._serialized_start=82
  _globals['_GETVERSIONRESPONSE']._serialized_end=119
  _globals['_SETVERSIONREQUEST']._serialized_start=121
  _globals['_SETVERSIONREQUEST']._serialized_end=175
  _globals['_SETVERSIONRESPONSE']._serialized_start=177
  _globals['_SETVERSIONRESPONSE']._serialized_end=214
  _globals['_FUNCTIONVERSIONSERVICE']._serialized_start=217
  _globals['_FUNCTIONVERSIONSERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
