# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: create_get_version.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'create_get_version.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63reate_get_version.proto\x12\x12\x63reate_get_version\"M\n\x15\x43reateFunctionRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\")\n\x16\x43reateFunctionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"C\n\x19GetFunctionDetailsRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"c\n\x1aGetFunctionDetailsResponse\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07runtime\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t2\xff\x01\n\x11\x43reateGetServicer\x12n\n\x15\x43reateFunctionVersion\x12).create_get_version.CreateFunctionRequest\x1a*.create_get_version.CreateFunctionResponse\x12z\n\x19GetFunctionVersionDetails\x12-.create_get_version.GetFunctionDetailsRequest\x1a..create_get_version.GetFunctionDetailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'create_get_version_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEFUNCTIONREQUEST']._serialized_start=48
  _globals['_CREATEFUNCTIONREQUEST']._serialized_end=125
  _globals['_CREATEFUNCTIONRESPONSE']._serialized_start=127
  _globals['_CREATEFUNCTIONRESPONSE']._serialized_end=168
  _globals['_GETFUNCTIONDETAILSREQUEST']._serialized_start=170
  _globals['_GETFUNCTIONDETAILSREQUEST']._serialized_end=237
  _globals['_GETFUNCTIONDETAILSRESPONSE']._serialized_start=239
  _globals['_GETFUNCTIONDETAILSRESPONSE']._serialized_end=338
  _globals['_CREATEGETSERVICER']._serialized_start=341
  _globals['_CREATEGETSERVICER']._serialized_end=596
# @@protoc_insertion_point(module_scope)
