# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from archiveRestoreApi import archive_restore_pb2 as archive__restore__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in archive_restore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArchiveRestoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ArchiveFunctionVersion = channel.unary_unary(
                '/functionservice.ArchiveRestoreService/ArchiveFunctionVersion',
                request_serializer=archive__restore__pb2.FunctionRequest.SerializeToString,
                response_deserializer=archive__restore__pb2.FunctionResponse.FromString,
                _registered_method=True)
        self.RestoreArchivedVersion = channel.unary_unary(
                '/functionservice.ArchiveRestoreService/RestoreArchivedVersion',
                request_serializer=archive__restore__pb2.FunctionRequest.SerializeToString,
                response_deserializer=archive__restore__pb2.FunctionResponse.FromString,
                _registered_method=True)


class ArchiveRestoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ArchiveFunctionVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreArchivedVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArchiveRestoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ArchiveFunctionVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveFunctionVersion,
                    request_deserializer=archive__restore__pb2.FunctionRequest.FromString,
                    response_serializer=archive__restore__pb2.FunctionResponse.SerializeToString,
            ),
            'RestoreArchivedVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreArchivedVersion,
                    request_deserializer=archive__restore__pb2.FunctionRequest.FromString,
                    response_serializer=archive__restore__pb2.FunctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'functionservice.ArchiveRestoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('functionservice.ArchiveRestoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArchiveRestoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ArchiveFunctionVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functionservice.ArchiveRestoreService/ArchiveFunctionVersion',
            archive__restore__pb2.FunctionRequest.SerializeToString,
            archive__restore__pb2.FunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreArchivedVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/functionservice.ArchiveRestoreService/RestoreArchivedVersion',
            archive__restore__pb2.FunctionRequest.SerializeToString,
            archive__restore__pb2.FunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
