# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import function_versioning_pb2 as function__versioning__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in function_versioning_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FunctionVersioningStub(object):
    """Define the FunctionVersioning service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFunctionVersion = channel.unary_unary(
                '/function_versioning.FunctionVersioning/CreateFunctionVersion',
                request_serializer=function__versioning__pb2.CreateFunctionRequest.SerializeToString,
                response_deserializer=function__versioning__pb2.CreateFunctionResponse.FromString,
                _registered_method=True)
        self.GetFunctionVersionDetails = channel.unary_unary(
                '/function_versioning.FunctionVersioning/GetFunctionVersionDetails',
                request_serializer=function__versioning__pb2.GetFunctionDetailsRequest.SerializeToString,
                response_deserializer=function__versioning__pb2.GetFunctionDetailsResponse.FromString,
                _registered_method=True)


class FunctionVersioningServicer(object):
    """Define the FunctionVersioning service
    """

    def CreateFunctionVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFunctionVersionDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FunctionVersioningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFunctionVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFunctionVersion,
                    request_deserializer=function__versioning__pb2.CreateFunctionRequest.FromString,
                    response_serializer=function__versioning__pb2.CreateFunctionResponse.SerializeToString,
            ),
            'GetFunctionVersionDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunctionVersionDetails,
                    request_deserializer=function__versioning__pb2.GetFunctionDetailsRequest.FromString,
                    response_serializer=function__versioning__pb2.GetFunctionDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'function_versioning.FunctionVersioning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('function_versioning.FunctionVersioning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FunctionVersioning(object):
    """Define the FunctionVersioning service
    """

    @staticmethod
    def CreateFunctionVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/function_versioning.FunctionVersioning/CreateFunctionVersion',
            function__versioning__pb2.CreateFunctionRequest.SerializeToString,
            function__versioning__pb2.CreateFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFunctionVersionDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/function_versioning.FunctionVersioning/GetFunctionVersionDetails',
            function__versioning__pb2.GetFunctionDetailsRequest.SerializeToString,
            function__versioning__pb2.GetFunctionDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
