# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: function_versioning.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'function_versioning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66unction_versioning.proto\x12\x13\x66unction_versioning\"M\n\x15\x43reateFunctionRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\")\n\x16\x43reateFunctionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"C\n\x19GetFunctionDetailsRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"c\n\x1aGetFunctionDetailsResponse\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07runtime\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t2\x84\x02\n\x12\x46unctionVersioning\x12p\n\x15\x43reateFunctionVersion\x12*.function_versioning.CreateFunctionRequest\x1a+.function_versioning.CreateFunctionResponse\x12|\n\x19GetFunctionVersionDetails\x12..function_versioning.GetFunctionDetailsRequest\x1a/.function_versioning.GetFunctionDetailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'function_versioning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEFUNCTIONREQUEST']._serialized_start=50
  _globals['_CREATEFUNCTIONREQUEST']._serialized_end=127
  _globals['_CREATEFUNCTIONRESPONSE']._serialized_start=129
  _globals['_CREATEFUNCTIONRESPONSE']._serialized_end=170
  _globals['_GETFUNCTIONDETAILSREQUEST']._serialized_start=172
  _globals['_GETFUNCTIONDETAILSREQUEST']._serialized_end=239
  _globals['_GETFUNCTIONDETAILSRESPONSE']._serialized_start=241
  _globals['_GETFUNCTIONDETAILSRESPONSE']._serialized_end=340
  _globals['_FUNCTIONVERSIONING']._serialized_start=343
  _globals['_FUNCTIONVERSIONING']._serialized_end=603
# @@protoc_insertion_point(module_scope)
