# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: list_delete.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'list_delete.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11list_delete.proto\"+\n\x13listFunctionRequest\x12\x14\n\x0c\x66unctionName\x18\x01 \x01(\t\">\n\x15\x64\x65leteFunctionRequest\x12\x14\n\x0c\x66unctionName\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\":\n\x14\x66unctionVersionsInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x11\n\tcreatedAt\x18\x02 \x01(\t\"J\n\x1c\x66unctionListVersionsResponse\x12*\n\x0bversioninfo\x18\x01 \x03(\x0b\x32\x15.functionVersionsInfo\",\n\x16\x64\x65leteFunctionResponse\x12\x12\n\ndeleteBool\x18\x01 \x01(\x08\x32\xa0\x01\n\nlistDelete\x12M\n\x14listFunctionVersions\x12\x14.listFunctionRequest\x1a\x1d.functionListVersionsResponse\"\x00\x12\x43\n\x0e\x64\x65leteFunction\x12\x16.deleteFunctionRequest\x1a\x17.deleteFunctionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'list_delete_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTFUNCTIONREQUEST']._serialized_start=21
  _globals['_LISTFUNCTIONREQUEST']._serialized_end=64
  _globals['_DELETEFUNCTIONREQUEST']._serialized_start=66
  _globals['_DELETEFUNCTIONREQUEST']._serialized_end=128
  _globals['_FUNCTIONVERSIONSINFO']._serialized_start=130
  _globals['_FUNCTIONVERSIONSINFO']._serialized_end=188
  _globals['_FUNCTIONLISTVERSIONSRESPONSE']._serialized_start=190
  _globals['_FUNCTIONLISTVERSIONSRESPONSE']._serialized_end=264
  _globals['_DELETEFUNCTIONRESPONSE']._serialized_start=266
  _globals['_DELETEFUNCTIONRESPONSE']._serialized_end=310
  _globals['_LISTDELETE']._serialized_start=313
  _globals['_LISTDELETE']._serialized_end=473
# @@protoc_insertion_point(module_scope)
